resource_group_name = "dev_Organization"
virtual_network_name = "dev_vnetprod019"
subnet_name = "dev_subnet019"
network_interface_name = "dev_nicprod019"
public_ip_name = "dev_publicip019"
virtual_machine_name = "dev_linuxvm019"
