resource_group_name = "int_Organization"
virtual_network_name = "int_vnetprod019"
subnet_name = "int_subnet019"
network_interface_name = "int_nicprod019"
public_ip_name = "int_publicip019"
virtual_machine_name = "int_linuxvm019"
