resource_group_name = "prod_Organization"
virtual_network_name = "prod_vnetprod019"
subnet_name = "prod_subnet019"
network_interface_name = "prod_nicprod019"
public_ip_name = "prod_publicip019"
virtual_machine_name = "prod_linuxvm019"
